# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attribute.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='attribute.proto',
  package='Attribute',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x61ttribute.proto\x12\tAttribute\"\x9d\x02\n\x07Request\x12\x0e\n\x06\x64\x65tect\x18\x01 \x02(\x05\x12\r\n\x05width\x18\x02 \x02(\x05\x12\x0c\n\x04high\x18\x03 \x02(\x05\x12\r\n\x05image\x18\x04 \x02(\x0c\x12\x11\n\trequestid\x18\x05 \x02(\t\x12\x0f\n\x07\x64tthres\x18\x06 \x02(\x01\x12\r\n\x05\x64tnms\x18\x07 \x02(\x01\x12\x0c\n\x04\x61ttr\x18\x08 \x02(\x05\x12\x0e\n\x06\x61\x63tion\x18\t \x02(\x05\x12\x0f\n\x07\x63\x61rtype\x18\n \x02(\x05\x12\x0f\n\x07\x63\x61rmake\x18\x0b \x02(\x05\x12\x11\n\tmaxObjNum\x18\x0c \x02(\x05\x12\r\n\x05\x61ttrW\x18\r \x02(\x05\x12\r\n\x05\x61ttrH\x18\x0e \x02(\x05\x12\x11\n\tnmsmethod\x18\x0f \x02(\x05\x12\x10\n\x08nmssigma\x18\x10 \x02(\x01\x12\r\n\x05track\x18\x11 \x01(\x05\"\xad\x04\n\x08Response\x12\x11\n\trequestid\x18\x01 \x02(\t\x12*\n\x06status\x18\x02 \x02(\x0e\x32\x1a.Attribute.Response.Status\x12,\n\x05\x64\x65tec\x18\x03 \x03(\x0b\x32\x1d.Attribute.Response.Detection\x1a\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x1a\xdb\x02\n\tDetection\x12%\n\x02p1\x18\x01 \x02(\x0b\x32\x19.Attribute.Response.Point\x12%\n\x02p2\x18\x02 \x02(\x0b\x32\x19.Attribute.Response.Point\x12%\n\x02p3\x18\x03 \x02(\x0b\x32\x19.Attribute.Response.Point\x12%\n\x02p4\x18\x04 \x02(\x0b\x32\x19.Attribute.Response.Point\x12\x31\n\x05\x61ttrs\x18\x05 \x03(\x0b\x32\".Attribute.Response.Detection.Attr\x12\x10\n\x08obj_name\x18\x06 \x02(\t\x12\r\n\x05score\x18\x07 \x02(\x01\x12\x13\n\x0b\x66\x65\x61ture_dim\x18\x08 \x02(\x05\x12\x13\n\x0b\x66\x65\x61ture_val\x18\t \x03(\x02\x12\x0f\n\x07trackID\x18\n \x02(\x05\x1a#\n\x04\x41ttr\x12\x0c\n\x04name\x18\x01 \x02(\x05\x12\r\n\x05score\x18\x02 \x02(\x01\"7\n\x06Status\x12\n\n\x06RES_OK\x10\x00\x12\r\n\tRES_ERROR\x10\x01\x12\x12\n\x0eRES_PARAMERROR\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Attribute.Response.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RES_OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RES_PARAMERROR', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=821,
  serialized_end=876,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_STATUS)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Attribute.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detect', full_name='Attribute.Request.detect', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='Attribute.Request.width', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='high', full_name='Attribute.Request.high', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='Attribute.Request.image', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestid', full_name='Attribute.Request.requestid', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtthres', full_name='Attribute.Request.dtthres', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtnms', full_name='Attribute.Request.dtnms', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='Attribute.Request.attr', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='Attribute.Request.action', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cartype', full_name='Attribute.Request.cartype', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='carmake', full_name='Attribute.Request.carmake', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxObjNum', full_name='Attribute.Request.maxObjNum', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attrW', full_name='Attribute.Request.attrW', index=12,
      number=13, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attrH', full_name='Attribute.Request.attrH', index=13,
      number=14, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nmsmethod', full_name='Attribute.Request.nmsmethod', index=14,
      number=15, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nmssigma', full_name='Attribute.Request.nmssigma', index=15,
      number=16, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track', full_name='Attribute.Request.track', index=16,
      number=17, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=316,
)


_RESPONSE_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Attribute.Response.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Attribute.Response.Point.x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Attribute.Response.Point.y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=440,
  serialized_end=469,
)

_RESPONSE_DETECTION_ATTR = _descriptor.Descriptor(
  name='Attr',
  full_name='Attribute.Response.Detection.Attr',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Attribute.Response.Detection.Attr.name', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='Attribute.Response.Detection.Attr.score', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=784,
  serialized_end=819,
)

_RESPONSE_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='Attribute.Response.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p1', full_name='Attribute.Response.Detection.p1', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p2', full_name='Attribute.Response.Detection.p2', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p3', full_name='Attribute.Response.Detection.p3', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p4', full_name='Attribute.Response.Detection.p4', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attrs', full_name='Attribute.Response.Detection.attrs', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='obj_name', full_name='Attribute.Response.Detection.obj_name', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='Attribute.Response.Detection.score', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_dim', full_name='Attribute.Response.Detection.feature_dim', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_val', full_name='Attribute.Response.Detection.feature_val', index=8,
      number=9, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trackID', full_name='Attribute.Response.Detection.trackID', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_DETECTION_ATTR, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=819,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Attribute.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestid', full_name='Attribute.Response.requestid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='Attribute.Response.status', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='detec', full_name='Attribute.Response.detec', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_POINT, _RESPONSE_DETECTION, ],
  enum_types=[
    _RESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=876,
)

_RESPONSE_POINT.containing_type = _RESPONSE
_RESPONSE_DETECTION_ATTR.containing_type = _RESPONSE_DETECTION
_RESPONSE_DETECTION.fields_by_name['p1'].message_type = _RESPONSE_POINT
_RESPONSE_DETECTION.fields_by_name['p2'].message_type = _RESPONSE_POINT
_RESPONSE_DETECTION.fields_by_name['p3'].message_type = _RESPONSE_POINT
_RESPONSE_DETECTION.fields_by_name['p4'].message_type = _RESPONSE_POINT
_RESPONSE_DETECTION.fields_by_name['attrs'].message_type = _RESPONSE_DETECTION_ATTR
_RESPONSE_DETECTION.containing_type = _RESPONSE
_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_STATUS
_RESPONSE.fields_by_name['detec'].message_type = _RESPONSE_DETECTION
_RESPONSE_STATUS.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'attribute_pb2'
  # @@protoc_insertion_point(class_scope:Attribute.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(

  Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), dict(
    DESCRIPTOR = _RESPONSE_POINT,
    __module__ = 'attribute_pb2'
    # @@protoc_insertion_point(class_scope:Attribute.Response.Point)
    ))
  ,

  Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), dict(

    Attr = _reflection.GeneratedProtocolMessageType('Attr', (_message.Message,), dict(
      DESCRIPTOR = _RESPONSE_DETECTION_ATTR,
      __module__ = 'attribute_pb2'
      # @@protoc_insertion_point(class_scope:Attribute.Response.Detection.Attr)
      ))
    ,
    DESCRIPTOR = _RESPONSE_DETECTION,
    __module__ = 'attribute_pb2'
    # @@protoc_insertion_point(class_scope:Attribute.Response.Detection)
    ))
  ,
  DESCRIPTOR = _RESPONSE,
  __module__ = 'attribute_pb2'
  # @@protoc_insertion_point(class_scope:Attribute.Response)
  ))
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.Point)
_sym_db.RegisterMessage(Response.Detection)
_sym_db.RegisterMessage(Response.Detection.Attr)


# @@protoc_insertion_point(module_scope)
